name: HipsterBrown
markdown: redcarpet
pygments: true
exclude: ['sass', node_modules, README.md, package.json, Gruntfile.js, bower.json, bower_components]
gems: ['bourbon', 'bitters', 'neat']
permalink: /:categories/:title
