name: Deploy to Dokku - production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOKKU_HOST: 'hipsterbrown.com'
  DOKKU_APP_NAME: 'hipsterbrown.com'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: 'ssh://dokku@${{ env.DOKKU_HOST }}:22/${{ env.DOKKU_APP_NAME }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git-push-flags: --force
